### ISSUE TITLE
gl.FLOAT_VEC_2 should be gl.FLOAT_VEC2

### ISSUE THREAD

**Issue by justincui** [frzi/blinkjs#1]
const uniformsFnTable = {
	[gl.FLOAT]:                   'uniform1f',
	[gl.FLOAT_VEC_2]:             'uniform2f',
	[gl.FLOAT_VEC_3]:             'uniform3f',
	[gl.FLOAT_VEC_4]:             'uniform4f',

gl.FLOAT_VEC_2 should be gl.FLOAT_VEC2
gl.FLOAT_VEC_3 should be gl.FLOAT_VEC3
gl.FLOAT_VEC_4 should be gl.FLOAT_VEC4

**Comment by frzi** [comment]
Pfff. That's extremely embarrassing of me. Thanks for noticing. 😃
