### ISSUE TITLE
Errors Running in a React environment installed using npm.

### ISSUE THREAD

**Issue by FarazzShaikh** [frzi/blinkjs#12]
When including blink.js as -

```lang-js
import * as blink from 'blink.js';
```

I get the Error -

``` 
Error: Unable to compile vertex shader. Info log: ERROR: 0:3: '/' : syntax error

▼ 2 stack frames were expanded.
compileShader
     node_modules/blink.js/src/WebGL/Program.js:86

Module../node_modules/blink.js/src/WebGL/Program.js
     node_modules/blink.js/src/WebGL/Program.js:5
```

After further looking into i found this error is because of these lines -
https://github.com/frzi/blinkjs/blob/2f9884167a4b376c9f3f44eb97725478fd538532/src/WebGL/Program.js#L2
https://github.com/frzi/blinkjs/blob/2f9884167a4b376c9f3f44eb97725478fd538532/src/Kernel.js#L4

The imported shader is passed into -
https://github.com/frzi/blinkjs/blob/2f9884167a4b376c9f3f44eb97725478fd538532/src/WebGL/Program.js#L72-L91

it seems like importing the shaders in this way results in the shader becoming -
```
#version 300 es

/static/media/quad.75d70ea6.vert
``` 

This is fixed by exporting the shader as a string like -
``` lang-js
export default`#version 300 es

precision highp float;

out vec2 bl_UV;

void main() {
	float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = -1.0 + float((gl_VertexID & 2) << 1);
    gl_Position = vec4(x, y, 0, 1);
	bl_UV = gl_Position.xy * 0.5 + 0.5;
}`
```
this results in the correct behavior of the initial shaders being compiled as -
```
#version 300 es

precision highp float;

out vec2 bl_UV;

void main() {
	float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = -1.0 + float((gl_VertexID & 2) << 1);
    gl_Position = vec4(x, y, 0, 1);
	bl_UV = gl_Position.xy * 0.5 + 0.5;
}
```
I will submit a PR once i perform some more tests.

**Comment by frzi** [comment]
Blink.js never really was made to be bundled as-is with projects directly. Notice how the README only refers linking the compiled bundle. 😉   When building blink.js a [Rollup plugin will do exactly as your described fix](https://github.com/frzi/blinkjs/blob/master/rollup.config.js#L8).

I'd hate to change the shader files into Javascript files in the repository. 

Blink.js is due for a rewrite anyway (in Typescript this time). With Safari about to enable WebGL 2.0 by default it may be interesting to revisit this project soon! 😄

**Comment by FarazzShaikh** [comment]
Ah I see, it is available on NPM so I assumed it'd be ready to use as is like other packages. I'll be looking forward to the rewrite, maybe become a collaborator too 🤨

**Comment by FarazzShaikh** [comment]
Close #12
