### ISSUE TITLE
Outputs without consistent sizes

### ISSUE THREAD

**Issue by d4tocchini** [frzi/blinkjs#4]
Is there a particular reason for requiring consistent output buffer sizes?  Handling the case for inconsistent sizes could be supported with an impact to the API of only one additional option.  

On that note, what do you think of the allowing the kernel to be "sized by", not the consistent size of all output buffers, but by any of the input / output buffers or by an integer value? The generated vert shader, that ultimately sets up the iterable execution of the kernel, appears to be agnostic to the particulars of the bl_size.

I can see this being useful for a variety of usecases, mine in particular is based on a derivative of [this GPU-based Sparse Voxel Octree](http://www.seas.upenn.edu/~pcozzi/OpenGLInsights/OpenGLInsights-SparseVoxelization.pdf), where an input `voxel_fragment_list` is iterated over and outputs an updated `node_pool` where nodes that need subdividing are flagged. In this case, the output buffer size is unknown before `exec()` because multiple entries in the voxel_fragment_list will flag the same nodes and thus the iteration is based on the size of the input buffer... I could preallocate a large node_pool, but given the potential sparseness of voxelized data this would waste a lot of cycles. 

I may have time to proto an implementation, hopefully before you get to responding to this...

**Comment by frzi** [comment]
Please know my knowledge of WebGL (and OpenGL in general) is pretty limited; so please correct me on anything if I'm wrong.

The OpenGL ES 3.0 specs tells us, in section 4.4:
> If the attachment sizes are not all identical, the results of rendering are
defined only within the largest area that can fit in all of the attachments.
This area is defined as the intersection of rectangles having a lower left of
(0, 0) and an upper right of (width, height) for each attachment. Contents
of attachments outside this area are undefined after execution of a rendering
command (as defined in section 2.6).

The reason blink.js forces consistent output buffer sizes is to prevent confusion of 'why does my buffer contain gaps?' beforehand. If this behaviour is incorrect or if this limit is too restricted to most users, I guess there's little reason to keep the rule enforced.

The idea of giving the Kernel the option to be 'sized by' sounds interesting and very useful for certain compute cases. I'm looking forward to a prototype of such an implementation.

Thank you for your time!
