### ISSUE TITLE
can't use vector: 1 or vector: 2 on core i7 laptop

### ISSUE THREAD

**Issue by vincenzoml** [frzi/blinkjs#5]
I am running the very first example of blink.js (the one using vector: 1 and assigning to each output fragment its id). In console, I get a list of zeroes. On anoter machine, or using vector: 4 and manually setting each field of the vector, I get the expected result. In the javascript console, I get a warning:

Error: WebGL warning: readPixels: Incompatible format or type.

This is at line 840 in file dist/blink.js:

`gl.readPixels(0, 0, size[0], size[1], gl[format], gl[type], buffer.data, 0);`

 I then added a line before that one:

`console.log(gl[format], gl[type]);`

and here is the result:

`33319 5126`

That's all I know. I have a fairly standard 2013 laptop, intel core i7 4th generation with an intel integrated gpu. I am using chrome 62.0.3202.94 on ubuntu 17.10.

**Comment by frzi** [comment]
blink.js dependents heavily on the browser's WebGL 2 implementation. Which, unfortunately, is inconsistent between different browsers on different operating systems running on different hardware.

If you could, please open the `report.html` file found in the `test/` folder. This file runs a test for every value type + vector size combination. It should give a quick overview of which combinations are compatible, which return faulty values and which are unavailable in the browser. Keep in mind, the results vary between machines and browsers.

From the logged values you mentioned (`33319 5126`) it seems blink.js (or rather, the browser) is incapable of reading Float values with a vector size of 2.

I've yet to run blink.js on a machine and browser that fully supports this combination. :)

**Comment by vincenzoml** [comment]
Thanks a lot for quick reply (suggestion: why not dumping the supported combinations to console in case of errors?). 

Fuzzy question: in firefox I see no support for vector size 1. Do you think this is going to change in the future with more compatibility with glsl es 3.0, or in other words should I develop for vector size 1 on chrome and wait for more compatibility to run my program on other browsers, or should I just use four values because that's how the de facto standard appears to be?

**Comment by frzi** [comment]
I am unfortunately in no position to predict Firefox's, or any other browser's, future regarding the compatibility of value type + vector size combinations. :)
Opening `report.html` in Firefox on macOS shows an array of red lines. Yet, Firefox on Windows give a lot of green checkmarks. 

blink.js was mostly developed for in-house use, where consistent use of a particular browser (and operating system and even hardware) is often guaranteed.
