### ISSUE TITLE
Copy data to host takes time proportional to previous iterations of the same kernel

### ISSUE THREAD

**Issue by vincenzoml** [frzi/blinkjs#6]
I have an odd behaviour that I can't explain. I observed this with other frameworks (e.g. turbo.js, or gpu.js). I run a kernel which takes very few time (0.1 milliseconds on my laptop) using a DeviceBuffer (no intermediate data copy). The kernel uses the same buffer for input and output. I iterate it `k` times. After that, I copy the data to host for rendering. Data copy to host (just that call) takes time proportional to `k` whereas it should take constant time if I understand things correctly. 

Here is a .zip file with a quasi-minimal working example. There is a constant named `iters` in line 4 of main.js. Increasing the value of `iters` will make the call to `dbuffer.toHost` in line 60 take more and more. Open console first, to be able to see the logging of execution times, then ***click on the canvas*** to see timing measurements, then try to increase `k` (by very small amounts!), and ***click again on the canvas*** to see the bug. 

I'm running chrome on linux / intel card. In Firefox I observe also odd behaviour and huge cpu/gpu load, but I am unsure if it's only the call to toHost which is affected.

[blinkjs-bug.zip](https://github.com/frzi/blinkjs/files/1513155/blinkjs-bug.zip)

**Comment by vincenzoml** [comment]
Here is a really minimal working example consisting of a single .html file that can be loaded in browser. Here I use just one kernel, which only copies its input. I use a for loop (function `doStuff(iters)`) to call the kernel several times, and then read back data. I call function `doStuff(iters)` with different iters (1, 10, 50, 100). The time to compute, and to read back the data, is shown in the javascript console. 

```
<html>
<head>
  <script src="blink.js"></script>
</head>
<body>
<h1>Open javascript console</h1>
<script>
  /* global blink */
  let size = 4096 * 4096

  let dbuffer = new blink.DeviceBuffer({
    alloc: size,
    vector: 4,
    type: blink.FLOAT
  })

  let step = new blink.Kernel({
    input: { in_rgba: dbuffer },
    output: { out_rgba: dbuffer }
  }, `void main() {
          out_rgba = texture(in_rgba, bl_UV);
    }`)

  let vect = new Float32Array(size)

  function doStuff (iters) {
    var t0, deltat
    console.log(`Running ${iters} iterations...`)
    t0 = window.performance.now()
    for (let i = 0; i < iters; i++) {
      step.exec()
    }
    deltat = window.performance.now() - t0
    console.log('done in time: ' + deltat)

    console.log('copying data to host...')
    t0 = window.performance.now()
    dbuffer.toHost(vect) // FIXME: this should take constant time!
    deltat = window.performance.now() - t0
    console.log('done in time: ' + deltat)
    console.log('')
  }

  doStuff(1)
  doStuff(10)
  doStuff(50)
  doStuff(100)
</script>
</body>
</html>

```

**Comment by vincenzoml** [comment]
[UPDATE]: I've learned about the fact that opengl and webgl are asynchronous. Therefore I tried inserting a `gl.Flush()` followed by `gl.Finish()` *just before* the call to `gl.readPixels` in `Texture.read(data)`. This affects just slightly the issue, but the call to `gl.ReadPixels` still takes time proportional to the previous iterations, and almost all the time spent in copying data to GPU. Does this make sense? Is it the way it should be?

**Comment by frzi** [comment]
Yes, what is most likely happening here is that `gl.drawArray` merely uploads the commands to the device and returns ASAP. Whether they've been executed or not. Whereas `gl.readPixels` requires previous commands to have been executed. `gl.readPixels` will therefore block and return once the device is done executing its queued commands.

This is one of the 'magic' trademarks of OpenGL. Unlike the strict and direct graphics libraries (Vulkan, D3D12 and even Metal to some degree), OpenGL is pretty abstract in its design. It can therefore be pretty difficult to tell what exactly is happening under the hood.

**Comment by vincenzoml** [comment]
Yes, I'd like to add: don't even think of relying on gl.finish; won't work. BTW: is there a forum for discussing blinkjs? Besides being very promising, it's also well written and robust, so I'd like to continue to use it and maybe discuss outside github "issues"; e.g. discuss possible features and implementing these myself if needed. Also: it's almost impossible to find this library on google even knowing it. I have to open package.json and copy/paste the homepage to be able to find it. Maybe consider renaming the project.

**Comment by frzi** [comment]
Thanks for the comments! 

There's literally been zero marketing for blink.js. It was simply dropped on npm after its first build. You can tell by the history of downloads this package has had over the year. Most people likely stumble upon it by accident via the [gpgpu](https://www.npmjs.com/browse/keyword/gpgpu) tag on npmjs.com. 

Due to its inconsistent nature among browsers and systems, I don't think you should count on this project having a very bright future outside of a few very niche in-house uses. There's a chance however blink.js will play a bigger role once [the next WebGL](https://github.com/gpuweb/gpuweb) launches. Which aims to be a more stable, more coherent and more predictable GPU accelerated graphics and computing API.

With that said, please don't let that discourage you to use and further improve blink.js!
